# Network params
dim: 256
aggr: 'concat'
loss: 'softmax'
arch: '1-1-0'
act: 'relu'
bias: 'norm'

# Training params
lr: 0.01
dropout: 0.2
n_epochs: 30

# Sampling params
sample_coverage: 25
sampler: 'node'
sg_size: 8000

# Other
adj_norm: 'rw'

# Evaluation
eval_train_every: 15
eval_val_every: 1
