# Network
dim: 128
aggr: 'concat'
loss: 'softmax'
arch: '1-0-1-0'
act: 'relu'
bias: 'norm'

# Training params
lr: 0.01
dropout: 0.1
n_epochs: 30

# Sampling params
sample_coverage: 50
sampler: 'rw'
depth: 4
n_roots: 2000

# Other
adj_norm: 'sym'

# Epoch
eval_train_every: 15
eval_val_every: 1
